version: '3.8'
services:
    bookmarker-db:
      image: postgres:14-alpine
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=appdb
      ports:
        - "15432:5432"

# bookmarker-api container talks with bookmarker-db container through container post and not host port
# if only this file is executed
# go to database (additional configuration) or (Data Sources and Drivers)
# select postgresql
# change port to 15432
# user : postgres
# password : postgres
# database : appdb
# click on test connections
